### ISSUE TITLE
TODOs (v1.x)

### ISSUE THREAD

**Issue by jadef** [jadef/gold-miner#2]
## TODO
- [x] Better component/sass matching
- [x] plan data Storage
- [x] Hook up data
- [x] Format content
  - [ ] Find alternative to using dangerouslySetInnerHTML
- [x] Swap from browserify to webpack
  - [x] Switch to Yarn
  - [x] Play nice with browsersync
  - [x] Hot reloading
  - [x] Move Sass compile over
    - [x] Linting
    - [x] Sourcemaps
    - [x] break apart includes to component level (eek, doing it!)
    - [x] PostCSS (https://github.com/postcss/postcss-loader)
- [x] Get JS Linting implemented
- [x] Isolate entries for segmentation
- [ ] dynamic "edit" date stamp
- [x] build footer
- [ ] Controls
  - [x] Tags
    - [x] mobile tag drawer
  - [ ] Letters
    - [x] Disabled Letters
    - [x] First Active
    - [x] Only one Active at a time
    - [x] Move handle on click
    - [x] Map points
    - [ ] Update handle on scroll
    - [ ] update everything on tag filter?
- [x] Scroll swap/animations
- [ ] animate filtering of entries
- [ ] Testing suite
  - [ ] Set up CI (codeship, circleci or travis)
- [ ] Production env build
  - [ ] Gulp?
  - [ ] PostCSS (configured with env)
    - [ ] Configured with env - no sourcemaps
    - [ ] colorguard?
    - [ ] cssnano

## Refactor
- [ ] Single scroll event triggering
- [ ] reusable smooth scroll

## Bugs
- [x] Logo animation event triggering
- [ ] letter handle math drift
- [ ] header offset issue
